### ISSUE TITLE
Change in tests "Altom" name in imports for C# package

### ISSUE THREAD

**Issue by iulianatodoran** [alttester/EXAMPLES-NewInputSystem--LeanTouch-CSharp#5]
## Description
 
- Apply in tests the changes brought in the `feature-proxy` branch by https://github.com/alttester/AltTester-Unity-SDK/issues/984 for **the next release of the tester** (for pro 1.0 release)
- Update unitypackage
- Update README.md
## Additional info
- epic: https://github.com/alttester/AltTester-Unity-SDK/issues/1038
- the PR for this issue should be merged on the `main` branch only when we have the released tester for pro 1.0

**Comment by MihaiCuc98** [comment]
The testing session is done. The testing results can be seen in: https://github.com/alttester/EXAMPLES-NewInputSystem--LeanTouch-CSharp/pull/8

I will move this ticket into `Done`.
